### ISSUE TITLE
文件损坏&无相关文件

### ISSUE THREAD

**Issue by tingroger** [19PDP/Bilibili-plus#1]
1. STL视频的配套文档 Slide.pdf损坏
2.  C++新特性的视频无课件

**Comment by ZachL1** [comment]
> 1. STL视频的配套文档 Slide.pdf损坏
> 2. C++新特性的视频无课件

经验证，[Slide.pdf](https://github.com/19PDP/Bilibili-plus/tree/master/C%2B%2B-STL-HouJie/slide) 下载打开正常。损坏可能是下载过程导致，您可以尝试重新下载。
C++新特性的视频有 [课件](https://github.com/19PDP/Bilibili-plus/tree/master/C%2B%2B-newC%2B%2B11%2614-HouJie/slide)，但无源代码
