### ISSUE TITLE
houjie - C++STL - 23 和 25 视频的内容是一样的

### ISSUE THREAD

**Issue by Donoy** [19PDP/Bilibili-plus#13]
![image](https://user-images.githubusercontent.com/24365655/145713420-b6e0465f-653d-48de-92ad-577e6801bf57.png)

**Comment by chamip** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by ZachL1** [comment]
已在 README 中说明。

> STL部分：p25是重复了p23的，这里缺少p25的视频；p27就是p28的开头，但这里没有缺失，课程内容是连贯的，应该是原视频没剪辑好。
